// <auto-generated />
namespace WebApplication_cnt_sta_cty_Reg_layout_1175.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class popularcntctyreg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(popularcntctyreg));
        
        string IMigrationMetadata.Id
        {
            get { return "202502181904332_popularcntctyreg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
